# Generated by Django 3.1.5 on 2021-01-19 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210118_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='figcaptions',
            field=models.TextField(blank=True, help_text='Tiêu đề của hình ảnh', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(blank=True, help_text='mô tả ngắn gọn cho bài viết', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog/'),
        ),
    ]
