# Generated by Django 3.1.5 on 2021-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
