# Generated by Django 3.1.5 on 2021-05-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_accessiblechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessiblechoice',
            name='access',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
