# Generated by Django 3.1.5 on 2021-05-06 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_auto_20210506_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessiblechoice',
            name='email',
            field=models.EmailField(default=datetime.datetime(2021, 5, 6, 9, 39, 12, 777075, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessiblechoice',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Used', 'Used'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
